name: fragments
adopt-info: fragments
grade: stable
confinement: strict
base: core18

slots:
  dbus:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Fragments

apps:
  fragments:
    command: usr/bin/fragments
    extensions: [gnome-3-34]
    common-id: de.haeckerfelix.Fragments
    plugs:
      - network
      - network-bind
      - mount-observe
      - home
      - removable-media

parts:
  fragments:
    plugin: meson
    source: https://gitlab.gnome.org/World/Fragments.git
    source-type: git
    source-tag: "1.4"
    parse-info: [usr/share/metainfo/de.haeckerfelix.Fragments.appdata.xml]
    meson-parameters:
      - --prefix=/usr
    override-build: |
      sed --in-place '\|<id>de.haeckerfelix.Fragments</id>|a<icon type="stock">snap.fragments.de.haeckerfelix.Fragments</icon>' data/de.haeckerfelix.Fragments.appdata.xml.in
      sed --in-place 's|^Icon=.*|Icon=snap.fragments.de.haeckerfelix.Fragments|' data/de.haeckerfelix.Fragments.desktop.in
      snapcraftctl build
    override-prime: |
      snapcraftctl prime
      mkdir -p meta/gui
      cp -r usr/share/icons meta/gui/
      for i in `find meta/gui/icons -name "*.svg" -o -name "*.png"`
      do
        mv $i "`dirname $i`/snap.$SNAPCRAFT_PROJECT_NAME.`basename $i`"
      done

    build-packages:
      - cmake
      - libcurl4-openssl-dev
      - libssl-dev
      - libevent-dev
      - libappindicator-dev
    stage-packages:
      - libcurl4
      - libevent-2.1-6
      - libminiupnpc10
