name: fragments
adopt-info: fragments
grade: stable
confinement: strict
base: core22

slots:
  dbus:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Fragments

apps:
  fragments:
    command: usr/bin/fragments
    extensions: [gnome]
    common-id: de.haeckerfelix.Fragments
    plugs:
      - network
      - network-bind
      - mount-observe
      - home
      - removable-media

parts:
  fragments:
    plugin: meson
    source: https://gitlab.gnome.org/World/Fragments.git
    source-type: git
    source-tag: "2.0.2"
    parse-info: [usr/share/metainfo/de.haeckerfelix.Fragments.metainfo.xml]
    meson-parameters:
      - --prefix=/usr
    override-build: |
      wget https://sh.rustup.rs -O rustup-init.sh
      chmod +x rustup-init.sh
      ./rustup-init.sh -y
      source /root/.cargo/env
      sed --in-place '\|<id>@APP_ID@</id>|a<icon type="stock">snap.fragments.@APP_ID@</icon>' $CRAFT_PART_SRC/data/de.haeckerfelix.Fragments.metainfo.xml.in.in
      sed --in-place 's|^Icon=@APP_ID@|Icon=snap.fragments.@APP_ID@|' $CRAFT_PART_SRC/data/de.haeckerfelix.Fragments.desktop.in.in
      craftctl default
    override-prime: |
      craftctl default
      mkdir -p meta/gui
      cp -r usr/share/icons meta/gui/
      for i in `find meta/gui/icons -name "*.svg" -o -name "*.png"`
      do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

    build-packages:
      - cmake
      - meson
      - ninja-build
      - libcurl4-openssl-dev
      - libssl-dev
      - libevent-dev
      - libappindicator-dev
      - wget
    stage-packages:
      - libcurl4
      - libevent-2.1-7
      - libminiupnpc17
