name: fragments
adopt-info: fragments
grade: stable
confinement: strict
base: core22

slots:
  dbus:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Fragments

apps:
  fragments:
    command: usr/bin/fragments
    extensions: [gnome]
    common-id: de.haeckerfelix.Fragments
    plugs:
      - network
      - network-bind
      - mount-observe
      - home
      - removable-media

parts:
  transmission:
    plugin: autotools
    source: https://github.com/transmission/transmission.git
    source-type: git
    source-tag: "3.00"
    autotools-configure-parameters:
      - --without-gtk
      - --without-cli
      - --enable-daemon
      - --disable-nls
      - --prefix /usr
      - --disable-dependency-tracking
    override-build: |
      patch $CRAFT_PART_SRC/daemon/daemon.c $CRAFT_PROJECT_DIR/flatpak/transmission_pdeathsig.patch
      craftctl default

  fragments:
    plugin: meson
    source: https://gitlab.gnome.org/World/Fragments.git
    source-type: git
    source-tag: "2.0.2"
    parse-info: [usr/share/metainfo/de.haeckerfelix.Fragments.metainfo.xml]
    after: [rustup]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_BUILD/../../rustup/install/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_BUILD/../../rustup/install/usr/share/rust
    meson-parameters:
      - --prefix=/usr
    override-build: |
      sed --in-place '\|<id>@APP_ID@</id>|a<icon type="stock">snap.fragments.@APP_ID@</icon>' $CRAFT_PART_SRC/data/de.haeckerfelix.Fragments.metainfo.xml.in.in
      sed --in-place 's|^Icon=@APP_ID@|Icon=snap.fragments.@APP_ID@|' $CRAFT_PART_SRC/data/de.haeckerfelix.Fragments.desktop.in.in
      patch $CRAFT_PART_SRC/src/main.rs $CRAFT_PROJECT_DIR/fragments.patch
      craftctl default
    override-prime: |
      craftctl default
      mkdir -p meta/gui
      cp -r usr/share/icons meta/gui/
      for i in `find meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-packages:
      - cmake
      - meson
      - ninja-build
      - libcurl4-openssl-dev
      - libssl-dev
      - libevent-dev
      - libappindicator-dev
      - wget
    stage-packages:
      - libcurl4
      - libevent-2.1-7
      - libminiupnpc17

  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
