name: fragments
adopt-info: fragments
grade: stable
confinement: strict
base: core22
compression: lzo

slots:
  dbus:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Fragments

environment:
  OPENSSL_CONF: ${SNAP}/etc/openssl.cnf
  HOME: ${SNAP_REAL_HOME}

apps:
  fragments:
    command: usr/bin/fragments
    extensions: [gnome]
    common-id: de.haeckerfelix.Fragments
    plugs:
      - network
      - network-bind
      - mount-observe
      - home
      - removable-media
      - desktop

parts:
  transmission:
    plugin: autotools
    source: https://github.com/transmission/transmission.git
    source-type: git
    source-tag: "3.00"
    autotools-configure-parameters:
      - --without-gtk
      - --without-cli
      - --enable-daemon
      - --prefix /usr
    build-packages:
      - libcurl4-openssl-dev
      - libssl-dev
      - libevent-dev
      - libminiupnpc-dev
      - intltool
      - pkg-config
      - zlib1g-dev
    override-build: |
      patch -p1 -d $CRAFT_PART_BUILD < $CRAFT_PROJECT_DIR/flatpak/transmission_pdeathsig.patch
      patch -p1 -d $CRAFT_PART_BUILD < $CRAFT_PROJECT_DIR/transmission.patch
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/etc
      cp $CRAFT_PROJECT_DIR/openssl.cnf $CRAFT_PART_INSTALL/etc/openssl.cnf
    stage-packages:
      - libcurl4
      - libevent-2.1-7
      - libminiupnpc17

  fragments:
    plugin: meson
    source: https://gitlab.gnome.org/World/Fragments.git
    source-type: git
    parse-info: [usr/share/metainfo/de.haeckerfelix.Fragments.metainfo.xml]
    after: [rustup]
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/usr
    override-build: |
      patch -p1 -d $CRAFT_PART_SRC < $CRAFT_PROJECT_DIR/fragments.patch
      craftctl default
    override-prime: |
      craftctl default
      mkdir -p meta/gui
      cp -r usr/share/icons meta/gui/
      for i in `find meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-packages:
      - cmake
      - meson
      - ninja-build
      - libfreetype6-dev

  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  cleanup: # https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280
    after:
      - fragments
      - transmission
      - rustup
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - gnome-42-2204-sdk
      - core22
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gnome-42-2204-sdk"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      for CRUFT in lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
