name: fragments
adopt-info: fragments
grade: stable
confinement: strict
base: core24
compression: lzo

slots:
  dbus:
    interface: dbus
    bus: session
    name: de.haeckerfelix.Fragments

apps:
  fragments:
    command: usr/bin/fragments
    extensions: [gnome]
    common-id: de.haeckerfelix.Fragments
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  transmission:
    plugin: cmake
    source: https://github.com/transmission/transmission.git
    source-type: git
    source-tag: "4.0.6"
    cmake-parameters:
      - -DENABLE_CLI=OFF
      - -DENABLE_TESTS=OFF
      - -DENABLE_MAC=OFF
      - -DENABLE_DAEMON=ON
      - -DENABLE_GTK=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libcurl4-openssl-dev
      - libssl-dev
      - libevent-dev
      - libminiupnpc-dev
      - intltool
    override-pull: |
      craftctl default
      curl https://gitlab.gnome.org/World/Fragments/-/raw/main/build-aux/flatpak/transmission_pdeathsig.patch | patch -p1 -d $CRAFT_PART_SRC
    stage-packages:
      - libcurl4
      - libevent-2.1-7
      - libminiupnpc17

  fragments:
    plugin: meson
    source: https://gitlab.gnome.org/World/Fragments.git
    source-type: git
    parse-info: [usr/share/metainfo/de.haeckerfelix.Fragments.metainfo.xml]
    after: [rustup]
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - curl
      - zlib1g-dev
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      craftctl default
      patch -p1 -d $CRAFT_PART_SRC < $CRAFT_PROJECT_DIR/fragments.patch
    override-prime: |
      craftctl default
      mkdir -p meta/gui
      cp -r usr/share/icons meta/gui/
      for i in `find meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  cleanup: # https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280
    after:
      - fragments
      - transmission
      - rustup
    plugin: nil
    build-snaps:
      - gnome-46-2404
      - gtk-common-themes
      - core24
    override-prime: |
      set -eux
      for snap in "core24" "gnome-46-2404" "gtk-common-themes"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      for CRUFT in lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
