name: Snapcraft build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: snapcore/action-build@v1
      id: snapcraft
      env:
        SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: '1'
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
